stub ready and working
replikation/What_the_Phage pull request #139
Opened 2021-08-17 10:36 UTC by mult1fractal

* included stub statements to relevant modules
* stub works 
* channels are correct

2021-08-17 12:39 UTC, replikation commented
@mult1fractal if stub is working please add it to the gitaction workflow as a dry run
* use this code as a reference, otherwise the stub is a bit pointless without it [link](https://github.com/replikation/poreCov/blob/master/.github/workflows/DryRun.yml)

2021-08-17 12:41 UTC, replikation commented on modules/databases/download_checkV_DB.nf
> +        mkdir checkv-db-v0.6
use `mkdir -p checkv-db-v0.6`  otherwise you get a error if a dir exists

2021-08-17 12:41 UTC, replikation commented on modules/databases/download_pvog_DB.nf
> +        mkdir pvogs
see above

2021-08-17 12:41 UTC, replikation commented on modules/databases/phage_references_blastDB.nf
> +        tar czf blast_database.tar.gz phage_blast_DB/
this doesnt seem right

2021-08-17 12:42 UTC, replikation commented on modules/databases/ppr_download_dependencies.nf
> +        mkdir PPR-Meta
see above

2021-08-17 12:42 UTC, replikation commented on modules/databases/virsorter2_download_DB.nf
> +        mkdir db
-p

2021-08-17 12:44 UTC, replikation commented on modules/raw_data_collection/pprmeta_collect_data.nf
> +    stub:
in this cases i would create a dummy result file in ppr meta process and don't add "stub:" here so the dry run will run the actual parser script

2021-08-17 12:46 UTC, replikation commented on nextflow.config
> +        params{
you wrote `params.params.cores = 2`   it should be only ``params.cores = 2``

2021-08-17 12:47 UTC, replikation requested changes
add into the stub genome this so its not an empty file:

> stubgenome
ATGC

2021-08-23 11:45 UTC, mult1fractal commented
I will merge it bc in my poreCov rework the annotation part will get a new layout as discussed, so the score based chunking will be exchanged by  "how many tools match per contig" and this will then replace the score based chunking (which currently fails the --annotate syntax check)

2021-08-23 12:00 UTC, merged